name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm run bootstrap
      - run: npm run lint
      - run: npm --prefix app run build
      - run: npm --prefix server run build || true
      - run: npm --prefix app run test
