name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install root dependencies
        run: npm ci
      - name: Bootstrap workspaces
        run: npm run bootstrap
      - name: Lint
        run: npm run lint
      - name: Build app
        run: npm --prefix app run build
      - name: Build server
        run: npm --prefix server run build || true
      - name: Run tests
        run: npm --prefix app run test
