name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Manual triggering
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Avoid running this workflow when the actor is the GitHub Actions bot
    if: github.actor != 'github-actions[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Ensure we have full history for deploy logs if needed
          fetch-depth: 0
      - name: Ensure we're building latest main
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main
      - name: Preflight diagnostics
        run: |
          set -x
          echo "---- Git info ----"
          git status --porcelain || true
          git rev-parse --abbrev-ref HEAD || true
          git rev-parse HEAD || true
          git log -1 --pretty=oneline || true

          echo "---- Actions / Env ----"
          echo "GITHUB_REF=${GITHUB_REF:-}" || true
          echo "GITHUB_SHA=${GITHUB_SHA:-}" || true
          echo "GITHUB_ACTOR=${GITHUB_ACTOR:-}" || true
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME:-}" || true
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE:-}" || true

          echo "---- Node / NPM / PATH ----"
          node -v || true
          npm -v || true
          which node || true
          which npm || true
          echo "NODE_PATH=$(node -e \"console.log(process.env.NODE_PATH||'')\")" || true
          echo "PATH=$PATH"
          npm config ls -l || true

          echo "---- Package & lockfile summaries ----"
          jq -r '.name+"@"+.version' package.json || true
          sed -n '1,120p' package.json || true
          sed -n '1,120p' app/package.json || true
          if [ -f package-lock.json ]; then sha1sum package-lock.json || true; fi
          if [ -f app/package-lock.json ]; then sha1sum app/package-lock.json || true; fi

          echo "---- node_modules layout (top-level and app) ----"
          ls -la || true
          ls -la node_modules || true
          ls -la app || true
          ls -la app/node_modules || true
          ls -la server/node_modules || true

          echo "---- npm global/workspace listing (top-level) ----"
          npm ls --depth=0 || true
          echo "---- npm workspace (app) ----"
          npm --workspace=app ls --depth=0 || true
          set +x
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            app/node_modules
            server/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'app/package-lock.json', 'server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Install dependencies
        run: |
          # First install root dependencies (include dev deps so workspace dev deps are available)
          npm ci --include=dev
          # Then install app-specific dependencies (include dev deps so vite is available locally)
          cd app
          npm ci --include=dev
          # Also install server dependencies (include dev deps)
          cd ../server
          npm ci --include=dev
          
      - name: Build
        run: |
          set -e
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "Environment vars relevant to Node/Vite"
          echo "PWD=$(pwd)"
          echo "BASE_URL=${BASE_URL:-$(node -e "console.log(process.env.BASE_URL||'unset')")}" || true
          echo "Installing root dependencies (including dev)"
          npm ci --include=dev
          echo "Root node_modules path contents (top-level)"
          ls -la node_modules || true
          echo "Check where vite is (npm ls vite)"
          npm ls vite --depth=0 || true
          echo "Attempt to resolve vite from node's resolver"
          node -e "try{console.log(require.resolve('vite'))}catch(e){console.error('resolve error:',e.message);process.exit(0)}"
          echo "Show app/package.json (for workspace config)"
          sed -n '1,200p' app/package.json || true
          echo "Running app workspace install and build"
          # Ensure app workspace dependencies are installed (non-hoisted where appropriate)
          npm --workspace=app ci --include=dev || true
          echo "Running build via npm workspace (this runs the script defined in app/package.json)"
          if npm --workspace=app run build --silent; then
            echo "npm workspace build succeeded"
          else
            echo "npm workspace build failed; falling back to running vite from app directory with npx"
            (cd app && npx --yes vite build) 
          fi
          echo "Listing app/dist contents"
          ls -la app/dist || true
          
      - name: Configure for GitHub Pages
        working-directory: ./app/dist
        run: |
          # Create a .nojekyll file to prevent Jekyll processing
          touch .nojekyll
          # Create a CNAME file if you have a custom domain
          # echo "yourdomain.com" > CNAME
          # Create a custom 404 page that redirects to index.html for SPA routing
          cp index.html 404.html

      - name: Verify build output
        run: |
          echo "Checking if dist directory exists..."
          if [ -d "app/dist" ]; then
            echo "✅ app/dist directory exists"
            ls -la app/dist
          else
            echo "❌ app/dist directory does not exist"
            exit 1
          fi
      - name: Pre-deploy cleanup & diagnostics
        run: |
          set -x
          echo "---- git / worktree diagnostics ----"
          git --version || true
          git status --porcelain -b || true
          echo "Current git worktrees:" || true
          git worktree list || true
          echo "Listing runner workspace root:" || true
          ls -la || true
          echo "Looking for temp deployment folder used by action (if present)" || true
          TMPFOLDER="github-pages-deploy-action-temp-deployment-folder"
          if [ -d "$TMPFOLDER" ]; then
            echo "$TMPFOLDER exists. Showing details:" || true
            ls -la "$TMPFOLDER" || true
            echo "Attempting to fix permissions and remove the folder to avoid git worktree errors" || true
            chmod -R +rw "$TMPFOLDER" || true
            rm -rf "$TMPFOLDER" || true
            # If git still thinks the worktree exists, prune and try to remove again
            git worktree prune || true
            git worktree list || true
          else
            echo "$TMPFOLDER not present; nothing to remove" || true
          fi
          echo "Show refs/branches pointing at gh-pages (if any)" || true
          git show-ref --heads | grep gh-pages || true
          echo "---- end pre-deploy diagnostics ----"
          set +x
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: app/dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic token
          commit-message: "Deploy to GitHub Pages [skip ci]"

      - name: Smoke test deployed site
        run: |
          set -e
          # Try the default GitHub Pages URL and the repository URL
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name || github.repository }}"
          # Construct likely Pages URL (user/organization page will differ if it's a user site)
          GH_PAGES_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "Checking ${GH_PAGES_URL}"
          curl -I --max-time 10 "${GH_PAGES_URL}" | head -n 5 || true
          # Also check root domain if CNAME present (optional)
          if [ -f "app/dist/CNAME" ]; then
            CUSTOM_DOMAIN=$(cat app/dist/CNAME | tr -d '\n')
            echo "Custom domain detected: ${CUSTOM_DOMAIN}"
            curl -I --max-time 10 "https://${CUSTOM_DOMAIN}" | head -n 5 || true
          else
            echo "No CNAME found; skipping custom domain check"
          fi
