name: Deploy PWA to GitHub Pages

on:
  workflow_dispatch:  # Manual triggering only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            app/node_modules
          key: ${{ runner.os }}-node-pwa-${{ hashFiles('package-lock.json', 'app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-pwa-
      
      - name: Install dependencies
        run: |
          # Install root dependencies (include dev deps)
          npm ci --include=dev
          # Install app dependencies (include dev deps so vite is available)
          cd app
          npm ci --include=dev
          # Install server dependencies (include dev deps)
          cd ../server
          npm ci --include=dev
          
      - name: Build PWA
        working-directory: ./app
        run: |
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "Listing app/node_modules/.bin"
          ls -la app/node_modules/.bin || true
          echo "Trying npx vite --version"
          npx vite --version || true
          npx --yes vite build
          
      - name: Prepare for GitHub Pages
        working-directory: ./app/dist
        run: |
          ls -la
          touch .nojekyll
          cp index.html 404.html
      
      - name: List build output files
        run: find app/dist -type f | sort
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
          publish_branch: gh-pages
          full_commit_message: "Deploy PWA to GitHub Pages [skip ci]"
