name: Build and Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main, master, deploy, fixes/pwa-db-fonts ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install root dependencies
        run: |
          npm ci

      - name: Build app
        env:
          # Optional: set this secret to point the built app at a live API endpoint
          VITE_API_BASE: ${{ secrets.DEPLOY_VITE_API_BASE || '' }}
        run: |
          cd app
          npm ci
          npm run build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/dist

  deploy-pages:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
